<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../CloudSDK/Objects/Data/UserData.cs" Link="Production/UserData.cs" />
    <Compile Include="../../CloudSDK/Objects/Network/Requests/LeaderboardRequests.cs" Link="Production/LeaderboardRequests.cs" />
    <Compile Include="../../CloudSDK/Transport/LeaderboardTransportContract.cs" Link="Production/LeaderboardTransportContract.cs" />
    <Compile Include="../../CloudSDK/Objects/Network/Requests/GiftCodeRequests.cs" Link="Production/GiftCodeRequests.cs" />
    <Compile Include="../../CloudSDK/Transport/GiftCodeTransportContract.cs" Link="Production/GiftCodeTransportContract.cs" />
    <Compile Include="../../CloudSDK/Objects/Network/Requests/PlayerProfileRequests.cs" Link="Production/PlayerProfileRequests.cs" />
    <Compile Include="../../CloudSDK/Objects/Network/Responses/PlayerProfileResponses.cs" Link="Production/PlayerProfileResponses.cs" />
    <Compile Include="../../CloudSDK/Transport/PlayerProfileTransportContract.cs" Link="Production/PlayerProfileTransportContract.cs" />
    <Compile Include="../../CloudSDK/Objects/Network/Requests/ValidatedActionsRequests.cs" Link="Production/ValidatedActionsRequests.cs" />
    <Compile Include="../../CloudSDK/Objects/Network/Responses/ValidatedActionsResponses.cs" Link="Production/ValidatedActionsResponses.cs" />
    <Compile Include="../../CloudSDK/Transport/ValidatedActionsTransportContract.cs" Link="Production/ValidatedActionsTransportContract.cs" />
  </ItemGroup>
</Project>
